name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  contracts:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0

    # Start node
    - name: Era Test Node Action
      uses: dutterbutter/era-test-node-action@v1

    # Setup pnpm
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/Iron
        cache: 'pnpm'

    # Install dependencies for contracts/gateway/sdk
    - name: Install contracts dependencies
      run: pnpm install --frozen-lockfile

    # Build SDK
    - name: Build SDK
      working-directory: ./packages/sdk
      run: pnpm run build:cjs

    # Start the Gateway
    - name: Run Gateway in the background
      run: |
        npx nx dev gateway --port 3002 &
        for attempt in {1..20}; do sleep 1; if (curl localhost:3002| head -n1 | grep -Ev 'Nuxt Dev server is starting...|Starting Nuxt...'); then echo ready; break; fi; echo waiting...; done

    # Run e2e tests
    - name: Run e2e test
      run: npx nx test contracts
