name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  contracts:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0

    # Start node
    - name: Era Test Node Action
      uses: dutterbutter/era-test-node-action@v1
      with:
        mode: 'fork'
        network: 'sepolia-testnet'

    # NPM install for contracts/gateway/sdk
    - name: Use latest Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/Iron
        cache: 'npm'
    - name: Install contracts dependencies
      working-directory: ./packages/contracts
      run: npm ci
    - name: Install gateway dependencies
      working-directory: ./packages/gateway
      run: npm ci
    - name: Install sdk dependencies
      working-directory: ./packages/sdk
      run: npm ci
    
    # Build SDK
    - name: Build SDK
      working-directory: ./packages/sdk
      run: npm run build

    # Link SDK to other packages
    - name: Link SDK to contracts
      run: |
        cd packages/sdk
        npm link
        cd ../contracts
        npm link zksync-account
    - name: Link SDK to gateway
      run: |
        cd packages/sdk
        npm link
        cd ../gateway
        npm link zksync-account

    # Start the Gateway
    - name: Run Gateway in the background
      working-directory: ./packages/gateway
      run: |
        npm run dev &
        for attempt in {1..20}; do sleep 1; if (curl localhost:3000| head -n1 | grep -Ev 'Nuxt Dev server is starting...|Starting Nuxt...'); then echo ready; break; fi; echo waiting...; done
    
    # Running a hardhat deploy command before running deployments in ethers tests appears
    # to fix something related to the transaction (related? https://github.com/matter-labs/tutorials/issues/25)
    - name: Initialize smart contracts on node
      working-directory: ./packages/contracts
      run: npm run deployFactoryAccount

    - name: Run e2e test
      working-directory: ./packages/contracts
      run: npm run test

