name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/Iron'
          cache: 'npm'

      - run: npm ci

      # Nx Affected runs only tasks affected by the changes in this PR/commit.
      # Learn more: https://nx.dev/ci/features/affected
      - run: npm exec nx affected -t test build

